### ISSUE TITLE
HTTP proxy functionality not working

### ISSUE THREAD

**Issue by fgeek** [gbrindisi/xsssniper#7]
As discussed in private email HTTP proxy functionality is not working. I have tested this with Burp and OWASP ZAP HTTP proxies with Git revision 73. I used these commands and no traffic is shown in logs of the proxy application:
```
xsssniper.py --http-proxy=127.0.0.1:8080 -u https://public-firing-range.appspot.com/
xsssniper.py --http-proxy=http://127.0.0.1:8080 -u https://public-firing-range.appspot.com/
xsssniper.py --http-proxy="http://127.0.0.1:8080" -u https://public-firing-range.appspot.com/
```

**Comment by gbrindisi** [comment]
Looks like there is a problem in mechanize proxy support.

Current code is here: https://github.com/gbrindisi/xsssniper/blob/master/core/scanner.py#L199

Should maybe be something like this avoiding the ProxyHandler:
```
req = mechanize.Request("http://www.google.com")
req.set_proxy("localhost:8888","http")
mechanize.urlopen(req)
```

**Comment by fgeek** [comment]
This is now working. I don't know what I did wrong previously. Sorry about noise.
